// src/data/mockdata.ts

import {
  Smartphone,
  Home,
  Utensils,
  Leaf,
  Shirt,
  BookOpen,
  Tv,
  Dumbbell,
  Baby,
  Car,
  Music,
  Camera,
  Gamepad2,
  Watch,
  Laptop,
  Sofa,
  Sparkles,
  Blocks,
  Briefcase,
  Lightbulb,
  PawPrint,
  Plane,
  Wrench,
  HeartPulse,
  ShoppingBasket,
  Palette,
  Tent,
  Footprints,
  Gem,
  Archive,
  Sparkle,
  PenLine,
  Wifi,
  Headphones,
  Bike,
  PersonStanding,
  House,
  Printer,
  Tablet,
} from "lucide-react";

import type { CategoryItem } from "@/components/organisms/CategoryRail";
import type { HeroBannerProps } from "@/components/organisms/HeroBanner";
import type {
  SeasonTab,
  SeasonProduct,
} from "@/components/organisms/SeasonSavingsCarousel";

/* ─── Category Rail ──────────────────────────────────────────── */

export const CATEGORY_ITEMS: CategoryItem[] = [
  {
    id: "electronics",
    label: "Electronics",
    icon: Smartphone,
    src: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=80&h=80&fit=crop",
    count: 5,
  },
  { id: "home", label: "Home & Living", icon: Home },
  { id: "kitchen", label: "Kitchen", icon: Utensils },
  { id: "garden", label: "Garden", icon: Leaf },
  {
    id: "fashion",
    label: "Fashion",
    icon: Shirt,
    src: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=80&h=80&fit=crop",
  },
  { id: "books", label: "Books", icon: BookOpen, count: 12 },
  { id: "tv", label: "TV & Audio", icon: Tv },
  {
    id: "sports",
    label: "Sports",
    icon: Dumbbell,
    src: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=80&h=80&fit=crop",
  },
  { id: "baby", label: "Baby", icon: Baby },
  { id: "automotive", label: "Automotive", icon: Car, count: 3 },
  { id: "music", label: "Music", icon: Music },
  {
    id: "cameras",
    label: "Cameras",
    icon: Camera,
    src: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=80&h=80&fit=crop",
  },
  { id: "gaming", label: "Gaming", icon: Gamepad2, count: 99 },
  { id: "watches", label: "Watches", icon: Watch },
  { id: "laptops", label: "Laptops", icon: Laptop },
  { id: "furniture", label: "Furniture", icon: Sofa },
  {
    id: "beauty",
    label: "Beauty",
    icon: Sparkles,
    src: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=80&h=80&fit=crop",
    count: 7,
  },
  { id: "toys", label: "Toys", icon: Blocks },
  { id: "office", label: "Office", icon: Briefcase, count: 2 },
  { id: "lighting", label: "Lighting", icon: Lightbulb },
  {
    id: "pets",
    label: "Pets",
    icon: PawPrint,
    src: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=80&h=80&fit=crop",
  },
  { id: "travel", label: "Travel", icon: Plane },
  { id: "tools", label: "Tools", icon: Wrench, count: 4 },
  { id: "health", label: "Health", icon: HeartPulse },
  {
    id: "grocery",
    label: "Grocery",
    icon: ShoppingBasket,
    src: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=80&h=80&fit=crop",
  },
  { id: "art", label: "Art & Craft", icon: Palette },
  { id: "outdoor", label: "Outdoor", icon: Tent, count: 6 },
  {
    id: "shoes",
    label: "Shoes",
    icon: Footprints,
    src: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=80&h=80&fit=crop",
  },
  { id: "jewelry", label: "Jewelry", icon: Gem, count: 1 },
  { id: "storage", label: "Storage", icon: Archive },
  { id: "cleaning", label: "Cleaning", icon: Sparkle },
  { id: "stationery", label: "Stationery", icon: PenLine },
  { id: "networking", label: "Networking", icon: Wifi },
  {
    id: "audio",
    label: "Headphones",
    icon: Headphones,
    src: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=80&h=80&fit=crop",
    count: 8,
  },
  { id: "cycling", label: "Cycling", icon: Bike },
  { id: "yoga", label: "Yoga", icon: PersonStanding },
  { id: "kids-fashion", label: "Kids Fashion", icon: Shirt },
  { id: "smart-home", label: "Smart Home", icon: House, count: 15 },
  { id: "printers", label: "Printers", icon: Printer },
  {
    id: "tablets",
    label: "Tablets",
    icon: Tablet,
    src: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=80&h=80&fit=crop",
  },
];

/* ─── Hero Banner ────────────────────────────────────────────── */

export type BannerSlide = Omit<HeroBannerProps, "className" | "children">;

export const BANNER_SLIDES: BannerSlide[] = [
  {
    eyebrow: "NEW COLLECTION",
    headline: "Grounded Living,",
    headlineAccent: "Elevated Design.",
    subheading:
      "Bring the tranquility of nature into your home with our sustainably sourced electronics and artisanal kitchenware.",
    backgroundImage: "/all.png",
    overlayOpacity: 0.3,
    backgroundColor: "#2d4a22",
    color: "secondary",
    align: "left",
    size: "lg",
    minHeight: "lg",
    actions: [
      {
        label: "Shop The Collection",
        href: "/collections/new",
        variant: "solid",
      },
      { label: "View Lookbook", href: "/lookbook", variant: "outline" },
    ],
  },
  {
    eyebrow: "TECH ESSENTIALS",
    headline: "Power Meets",
    headlineAccent: "Portability.",
    subheading:
      "Discover our curated range of ultra-thin laptops built for creators, developers, and professionals on the move.",
    backgroundImage: "/laptop.png",
    overlayOpacity: 0.2,
    backgroundColor: "#0f172a",
    color: "info",
    align: "left",
    size: "lg",
    minHeight: "lg",
    actions: [
      { label: "Shop Laptops", href: "/categories/laptops", variant: "solid" },
      {
        label: "Compare Models",
        href: "/categories/laptops/compare",
        variant: "outline",
      },
    ],
  },
  {
    eyebrow: "JUST ARRIVED",
    headline: "Your World,",
    headlineAccent: "In Your Pocket.",
    subheading:
      "The latest smartphones with all-day battery, pro-grade cameras, and displays that make everything look stunning.",
    backgroundImage: "/phone.png",
    overlayOpacity: 0.2,
    backgroundColor: "#3b0764",
    color: "secondary",
    align: "left",
    size: "xl",
    minHeight: "lg",
    actions: [
      { label: "Shop Mobiles", href: "/categories/mobiles", variant: "solid" },
      { label: "Trade In", href: "/trade-in", variant: "outline" },
    ],
  },
  {
    eyebrow: "BEAUTY EDIT",
    headline: "Confidence,",
    headlineAccent: "Redefined.",
    subheading:
      "From everyday essentials to statement looks — explore our clean beauty collection crafted for every skin tone.",
    backgroundImage: "/beauty.png",
    overlayOpacity: 0.2,
    backgroundColor: "#7c2d48",
    color: "danger",
    align: "left",
    size: "lg",
    minHeight: "lg",
    actions: [
      { label: "Shop Beauty", href: "/categories/beauty", variant: "solid" },
      { label: "Take the Quiz", href: "/beauty-quiz", variant: "outline" },
    ],
  },
  //   {
  //     // eyebrow: "BEAUTY EDIT",
  //     headline: "Confidence,",
  //     // headlineAccent: "Redefined.",
  //     subheading: "From everyday essentials to statement looks — explore our clean beauty collection crafted for every skin tone.",
  //     backgroundImage: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=1600&h=900&fit=crop",
  //     overlayOpacity: 0.5,
  //     backgroundColor: "#7c2d48",
  //     color: "danger",
  //     align: "left",
  //     size: "lg",
  //     minHeight: "lg",
  //     actions: [
  //       { label: "Shop Beauty",   href: "/categories/beauty", variant: "solid"   },
  //       { label: "Take the Quiz", href: "/beauty-quiz",       variant: "outline" },
  //     ],
  //   },
];

import type { DealTab, DealProduct } from "@/components/organisms/DealCarousel";

export const DEAL_TABS: DealTab[] = [
  { id: "electronics", label: "Electronics" },
  { id: "fashion", label: "Fashion" },
  { id: "home", label: "Home" },
  { id: "beauty", label: "Beauty" },
];

export const DEAL_PRODUCTS: DealProduct[] = [
  // ── Electronics ────────────────────────────────────────────
  {
    id: "p1",
    tabId: "electronics",
    title: "Wireless Noise-Cancelling Headphones",
    price: 49.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviewCount: 1284,
    image:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    imageAlt: "Wireless headphones",
    badges: [{ label: "50% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p1",
  },
  {
    id: "p2",
    tabId: "electronics",
    title: "Smart Watch Series 8",
    price: 129.99,
    originalPrice: 249.99,
    rating: 4.7,
    reviewCount: 856,
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
    imageAlt: "Smart watch",
    badges: [{ label: "48% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p2",
  },
  {
    id: "p3",
    tabId: "electronics",
    title: "Portable Bluetooth Speaker",
    price: 29.99,
    originalPrice: 59.99,
    rating: 4.3,
    reviewCount: 432,
    image:
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop",
    imageAlt: "Bluetooth speaker",
    badges: [{ label: "SALE", color: "warning" }],
    showAddToCart: true,
    href: "/products/p3",
  },
  {
    id: "p4",
    tabId: "electronics",
    title: "USB-C Fast Charging Cable 3-Pack",
    price: 9.99,
    originalPrice: 19.99,
    rating: 4.6,
    reviewCount: 3201,
    image:
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&h=400&fit=crop",
    imageAlt: "USB-C cables",
    showAddToCart: true,
    href: "/products/p4",
  },
  {
    id: "p5",
    tabId: "electronics",
    title: "Mechanical Gaming Keyboard",
    price: 59.99,
    originalPrice: 119.99,
    rating: 4.7,
    reviewCount: 2341,
    image:
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop",
    imageAlt: "Mechanical keyboard",
    badges: [{ label: "50% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p5",
  },
  {
    id: "p6",
    tabId: "electronics",
    title: "4K Webcam with Ring Light",
    price: 39.99,
    originalPrice: 79.99,
    rating: 4.4,
    reviewCount: 987,
    image:
      "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400&h=400&fit=crop",
    imageAlt: "4K webcam",
    badges: [{ label: "50% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p6",
  },
  {
    id: "p7",
    tabId: "electronics",
    title: "Wireless Ergonomic Mouse",
    price: 24.99,
    originalPrice: 49.99,
    rating: 4.5,
    reviewCount: 1543,
    image:
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop",
    imageAlt: "Wireless mouse",
    badges: [{ label: "50% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p7",
  },
  {
    id: "p8",
    tabId: "electronics",
    title: "Portable SSD 1TB",
    price: 69.99,
    originalPrice: 129.99,
    rating: 4.8,
    reviewCount: 3412,
    image:
      "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=400&h=400&fit=crop",
    imageAlt: "Portable SSD",
    badges: [
      { label: "46% OFF", color: "danger" },
      { label: "BESTSELLER", color: "success" },
    ],
    showAddToCart: true,
    href: "/products/p8",
  },
  {
    id: "p9",
    tabId: "electronics",
    title: "Noise-Cancelling Earbuds Pro",
    price: 44.99,
    originalPrice: 89.99,
    rating: 4.6,
    reviewCount: 2109,
    image:
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&h=400&fit=crop",
    imageAlt: "Earbuds",
    badges: [{ label: "50% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p9",
  },
  {
    id: "p10",
    tabId: "electronics",
    title: "Smart Home Hub Mini",
    price: 34.99,
    originalPrice: 59.99,
    rating: 4.3,
    reviewCount: 765,
    image:
      "https://images.unsplash.com/photo-1558089687-f282ffcbc0d6?w=400&h=400&fit=crop",
    imageAlt: "Smart home hub",
    badges: [{ label: "NEW", color: "info" }],
    showAddToCart: true,
    href: "/products/p10",
  },

  // ── Fashion ─────────────────────────────────────────────────
  {
    id: "p11",
    tabId: "fashion",
    title: "Classic Leather Sneakers",
    price: 44.99,
    originalPrice: 89.99,
    rating: 4.4,
    reviewCount: 672,
    image:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    imageAlt: "Leather sneakers",
    badges: [{ label: "50% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p11",
  },
  {
    id: "p12",
    tabId: "fashion",
    title: "Premium Wool Overcoat",
    price: 74.99,
    originalPrice: 149.99,
    rating: 4.8,
    reviewCount: 341,
    image:
      "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400&h=400&fit=crop",
    imageAlt: "Wool overcoat",
    badges: [{ label: "NEW", color: "success" }],
    showAddToCart: true,
    href: "/products/p12",
  },
  {
    id: "p13",
    tabId: "fashion",
    title: "Slim Fit Chino Trousers",
    price: 29.99,
    originalPrice: 59.99,
    rating: 4.3,
    reviewCount: 892,
    image:
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400&h=400&fit=crop",
    imageAlt: "Chino trousers",
    badges: [{ label: "50% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p13",
  },
  {
    id: "p14",
    tabId: "fashion",
    title: "Silk Blend Scarf",
    price: 19.99,
    originalPrice: 39.99,
    rating: 4.6,
    reviewCount: 234,
    image:
      "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop",
    imageAlt: "Silk scarf",
    showAddToCart: true,
    href: "/products/p14",
  },
  {
    id: "p15",
    tabId: "fashion",
    title: "Canvas Tote Bag",
    price: 14.99,
    originalPrice: 24.99,
    rating: 4.5,
    reviewCount: 1102,
    image:
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400&h=400&fit=crop",
    imageAlt: "Canvas tote bag",
    badges: [{ label: "40% OFF", color: "warning" }],
    showAddToCart: true,
    href: "/products/p15",
  },
  {
    id: "p16",
    tabId: "fashion",
    title: "Leather Bifold Wallet",
    price: 24.99,
    originalPrice: 49.99,
    rating: 4.7,
    reviewCount: 1876,
    image:
      "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&h=400&fit=crop",
    imageAlt: "Leather wallet",
    badges: [{ label: "50% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p16",
  },
  {
    id: "p17",
    tabId: "fashion",
    title: "Aviator Sunglasses",
    price: 19.99,
    originalPrice: 44.99,
    rating: 4.4,
    reviewCount: 543,
    image:
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=400&fit=crop",
    imageAlt: "Aviator sunglasses",
    badges: [{ label: "55% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p17",
  },
  {
    id: "p18",
    tabId: "fashion",
    title: "Merino Wool Beanie",
    price: 12.99,
    originalPrice: 24.99,
    rating: 4.6,
    reviewCount: 789,
    image:
      "https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=400&h=400&fit=crop",
    imageAlt: "Wool beanie",
    showAddToCart: true,
    href: "/products/p18",
  },

  // ── Home ────────────────────────────────────────────────────
  {
    id: "p19",
    tabId: "home",
    title: "Ceramic Pour-Over Coffee Set",
    price: 34.99,
    originalPrice: 59.99,
    rating: 4.9,
    reviewCount: 528,
    image:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=400&fit=crop",
    imageAlt: "Pour-over coffee set",
    badges: [{ label: "HOT", color: "warning" }],
    showAddToCart: true,
    href: "/products/p19",
  },
  {
    id: "p20",
    tabId: "home",
    title: "Linen Throw Pillow Set of 4",
    price: 24.99,
    originalPrice: 49.99,
    rating: 4.5,
    reviewCount: 219,
    image:
      "https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?w=400&h=400&fit=crop",
    imageAlt: "Linen throw pillows",
    showAddToCart: true,
    href: "/products/p20",
  },
  {
    id: "p21",
    tabId: "home",
    title: "Bamboo Kitchen Utensil Set",
    price: 14.99,
    originalPrice: 29.99,
    rating: 4.3,
    reviewCount: 445,
    image:
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop",
    imageAlt: "Bamboo kitchen utensils",
    showAddToCart: true,
    href: "/products/p21",
  },
  {
    id: "p22",
    tabId: "home",
    title: "Scented Soy Candle Set",
    price: 18.99,
    originalPrice: 34.99,
    rating: 4.8,
    reviewCount: 1023,
    image:
      "https://images.unsplash.com/photo-1603905861961-8a3f2c9f91f0?w=400&h=400&fit=crop",
    imageAlt: "Soy candles",
    badges: [{ label: "45% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p22",
  },
  {
    id: "p23",
    tabId: "home",
    title: "Stainless Steel Water Bottle 1L",
    price: 19.99,
    originalPrice: 39.99,
    rating: 4.7,
    reviewCount: 3876,
    image:
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop",
    imageAlt: "Steel water bottle",
    badges: [
      { label: "50% OFF", color: "danger" },
      { label: "ECO", color: "success" },
    ],
    showAddToCart: true,
    href: "/products/p23",
  },
  {
    id: "p24",
    tabId: "home",
    title: "Wooden Serving Board",
    price: 22.99,
    originalPrice: 44.99,
    rating: 4.6,
    reviewCount: 312,
    image:
      "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=400&h=400&fit=crop",
    imageAlt: "Wooden serving board",
    showAddToCart: true,
    href: "/products/p24",
  },
  {
    id: "p25",
    tabId: "home",
    title: "Blackout Curtain Pair",
    price: 29.99,
    originalPrice: 54.99,
    rating: 4.4,
    reviewCount: 678,
    image:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
    imageAlt: "Blackout curtains",
    badges: [{ label: "45% OFF", color: "warning" }],
    showAddToCart: true,
    href: "/products/p25",
  },
  {
    id: "p26",
    tabId: "home",
    title: 'Cast Iron Skillet 10"',
    price: 27.99,
    originalPrice: 49.99,
    rating: 4.9,
    reviewCount: 5201,
    image:
      "https://images.unsplash.com/photo-1585325701165-e7d23a83f2b6?w=400&h=400&fit=crop",
    imageAlt: "Cast iron skillet",
    badges: [
      { label: "44% OFF", color: "danger" },
      { label: "BESTSELLER", color: "success" },
    ],
    showAddToCart: true,
    href: "/products/p26",
  },

  // ── Beauty ──────────────────────────────────────────────────
  {
    id: "p27",
    tabId: "beauty",
    title: "Vitamin C Brightening Serum",
    price: 18.99,
    originalPrice: 39.99,
    rating: 4.6,
    reviewCount: 1893,
    image:
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop",
    imageAlt: "Vitamin C serum",
    badges: [{ label: "52% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p27",
  },
  {
    id: "p28",
    tabId: "beauty",
    title: "Matte Lipstick Collection — 6 Shades",
    price: 22.99,
    originalPrice: 44.99,
    rating: 4.4,
    reviewCount: 764,
    image:
      "https://images.unsplash.com/photo-1586495777744-4e6232bf8d53?w=400&h=400&fit=crop",
    imageAlt: "Matte lipstick collection",
    showAddToCart: true,
    href: "/products/p28",
  },
  {
    id: "p29",
    tabId: "beauty",
    title: "Hyaluronic Acid Moisturiser",
    price: 15.99,
    originalPrice: 29.99,
    rating: 4.7,
    reviewCount: 2341,
    image:
      "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?w=400&h=400&fit=crop",
    imageAlt: "Face moisturiser",
    badges: [{ label: "46% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p29",
  },
  {
    id: "p30",
    tabId: "beauty",
    title: "Rose Gold Makeup Brush Set — 12pc",
    price: 19.99,
    originalPrice: 39.99,
    rating: 4.5,
    reviewCount: 1120,
    image:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop",
    imageAlt: "Makeup brush set",
    badges: [{ label: "50% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p30",
  },
  {
    id: "p31",
    tabId: "beauty",
    title: "Retinol Night Repair Cream",
    price: 24.99,
    originalPrice: 49.99,
    rating: 4.8,
    reviewCount: 934,
    image:
      "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400&h=400&fit=crop",
    imageAlt: "Night cream",
    badges: [
      { label: "50% OFF", color: "danger" },
      { label: "CLEAN", color: "success" },
    ],
    showAddToCart: true,
    href: "/products/p31",
  },
  {
    id: "p32",
    tabId: "beauty",
    title: "Argan Oil Hair Mask",
    price: 11.99,
    originalPrice: 22.99,
    rating: 4.6,
    reviewCount: 1567,
    image:
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=400&h=400&fit=crop",
    imageAlt: "Hair mask",
    showAddToCart: true,
    href: "/products/p32",
  },
  {
    id: "p33",
    tabId: "beauty",
    title: "SPF 50 Tinted Sunscreen",
    price: 13.99,
    originalPrice: 26.99,
    rating: 4.7,
    reviewCount: 2876,
    image:
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop",
    imageAlt: "Tinted sunscreen",
    badges: [{ label: "48% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p33",
  },
  {
    id: "p34",
    tabId: "beauty",
    title: "Jade Facial Roller & Gua Sha Set",
    price: 16.99,
    originalPrice: 32.99,
    rating: 4.5,
    reviewCount: 743,
    image:
      "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400&h=400&fit=crop",
    imageAlt: "Jade roller set",
    badges: [{ label: "48% OFF", color: "danger" }],
    showAddToCart: true,
    href: "/products/p34",
  },
];

export const SEASON_TABS: SeasonTab[] = [
  { id: "__all__", label: "All" },
  { id: "summer", label: "Summer" },
  { id: "monsoon", label: "Monsoon" },
  { id: "festive", label: "Festive" },
];

export const SEASON_PRODUCTS: SeasonProduct[] = [
  {
    id: "p1",
    tabId: "summer",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/sample.jpg",
    imageAlt: "Cotton linen shirt, sky blue",
    title: "Cotton Linen Shirt",
    price: 1290,
    originalPrice: 1990,
    currency: "BDT",
    rating: 4.5,
    reviewCount: 128,
    badges: [{ label: "35% OFF", color: "danger" }],
    showAddToCart: true,
  },
  {
    id: "p2",
    tabId: "summer",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/shoes.jpg",
    imageAlt: "Breathable mesh sneakers, white",
    title: "Breathable Sneakers",
    price: 2450,
    originalPrice: 3200,
    currency: "BDT",
    rating: 4.2,
    reviewCount: 64,
    badges: [{ label: "New", color: "info" }],
    showAddToCart: true,
  },
  {
    id: "p3",
    tabId: "monsoon",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/bag.jpg",
    imageAlt: "Waterproof backpack, charcoal",
    title: "Waterproof Backpack",
    price: 1850,
    originalPrice: 2500,
    currency: "BDT",
    rating: 4.7,
    reviewCount: 95,
    badges: [{ label: "26% OFF", color: "danger" }],
    showAddToCart: true,
  },
  {
    id: "p4",
    tabId: "monsoon",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/umbrella.jpg",
    imageAlt: "Quick-dry compact umbrella, navy",
    title: "Quick-Dry Umbrella",
    price: 690,
    originalPrice: 990,
    currency: "BDT",
    rating: 4.0,
    reviewCount: 41,
    badges: [{ label: "30% OFF", color: "danger" }],
    showAddToCart: true,
  },
  {
    id: "p5",
    tabId: "festive",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/panjabi.jpg",
    imageAlt: "Embroidered panjabi, off-white",
    title: "Embroidered Panjabi",
    price: 2100,
    originalPrice: 2999,
    currency: "BDT",
    rating: 4.8,
    reviewCount: 210,
    badges: [
      { label: "30% OFF", color: "danger" },
      { label: "Bestseller", color: "secondary" },
    ],
    showAddToCart: true,
  },
  {
    id: "p6",
    tabId: "festive",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/saree.jpg",
    imageAlt: "Designer saree, maroon and gold",
    title: "Designer Saree",
    price: 3400,
    originalPrice: 4999,
    currency: "BDT",
    rating: 4.6,
    reviewCount: 173,
    badges: [{ label: "32% OFF", color: "danger" }],
    showAddToCart: true,
  },
  {
    id: "p7",
    tabId: "summer",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/sunglasses.jpg",
    imageAlt: "Aviator sunglasses, gold frame",
    title: "Aviator Sunglasses",
    price: 950,
    originalPrice: 1500,
    currency: "BDT",
    rating: 4.3,
    reviewCount: 58,
    badges: [{ label: "37% OFF", color: "danger" }],
    showAddToCart: true,
  },
  {
    id: "p8",
    tabId: "festive",
    // No image -> ProductCard renders its skeleton state
    title: "Leather Loafers",
    price: 2750,
    originalPrice: 3600,
    currency: "BDT",
    rating: 4.4,
    reviewCount: 87,
    badges: [{ label: "24% OFF", color: "danger" }],
    showAddToCart: true,
    isLoading: false,
  },
];

import type { GridProduct } from "@/components/organisms/ProductGrid";
import type { SortOption } from "@/components/molecules/SortDropdown";

export const GRID_SORT_OPTIONS: SortOption[] = [
  { value: "featured", label: "Most Relevant" },
  { value: "newest", label: "Newest" },
  { value: "price-asc", label: "Price: Low to High" },
  { value: "price-desc", label: "Price: High to Low" },
  { value: "rating", label: "Top Rated" },
];

export const GRID_PRODUCTS: GridProduct[] = [
  {
    id: "g1",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/sample.jpg",
    imageAlt: "Cotton linen shirt, sky blue",
    title: "Cotton Linen Shirt",
    price: 1290,
    originalPrice: 1990,
    currency: "BDT",
    rating: 4.5,
    reviewCount: 128,
    badges: [{ label: "35% OFF", color: "danger" }],
    showAddToCart: true,
  },
  {
    id: "g2",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/shoes.jpg",
    imageAlt: "Breathable mesh sneakers, white",
    title: "Breathable Sneakers",
    price: 2450,
    originalPrice: 3200,
    currency: "BDT",
    rating: 4.2,
    reviewCount: 64,
    badges: [{ label: "New", color: "info" }],
    showAddToCart: true,
  },
  {
    id: "g3",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/bag.jpg",
    imageAlt: "Waterproof backpack, charcoal",
    title: "Waterproof Backpack",
    price: 1850,
    originalPrice: 2500,
    currency: "BDT",
    rating: 4.7,
    reviewCount: 95,
    badges: [{ label: "26% OFF", color: "danger" }],
    showAddToCart: true,
  },
  {
    id: "g4",
    // No image -> exercises ProductCard's skeleton-on-missing-image path
    title: "Quick-Dry Umbrella",
    price: 690,
    originalPrice: 990,
    currency: "BDT",
    rating: 4.0,
    reviewCount: 41,
    badges: [{ label: "30% OFF", color: "danger" }],
    showAddToCart: true,
  },
  {
    id: "g5",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/panjabi.jpg",
    imageAlt: "Embroidered panjabi, off-white",
    title: "Embroidered Panjabi",
    price: 2100,
    originalPrice: 2999,
    currency: "BDT",
    rating: 4.8,
    reviewCount: 210,
    badges: [
      { label: "30% OFF", color: "danger" },
      { label: "Bestseller", color: "secondary" },
    ],
    showAddToCart: true,
  },
  {
    id: "g6",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/saree.jpg",
    imageAlt: "Designer saree, maroon and gold",
    title: "Designer Saree",
    price: 3400,
    originalPrice: 4999,
    currency: "BDT",
    rating: 4.6,
    reviewCount: 173,
    badges: [{ label: "32% OFF", color: "danger" }],
    showAddToCart: true,
  },
  {
    id: "g7",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/sunglasses.jpg",
    imageAlt: "Aviator sunglasses, gold frame",
    title: "Aviator Sunglasses",
    price: 950,
    originalPrice: 1500,
    currency: "BDT",
    rating: 4.3,
    reviewCount: 58,
    badges: [{ label: "37% OFF", color: "danger" }],
    showAddToCart: true,
  },
  {
    id: "g8",
    image:
      "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_fill/loafers.jpg",
    imageAlt: "Leather loafers, brown",
    title: "Leather Loafers",
    price: 2750,
    originalPrice: 3600,
    currency: "BDT",
    rating: 4.4,
    reviewCount: 87,
    badges: [{ label: "24% OFF", color: "danger" }],
    showAddToCart: true,
  },
];

import type { FilterSection } from "@/components/organisms/ProductFilterSidebar";

export const PRODUCT_FILTER_SECTIONS: FilterSection[] = [
  {
    id: "category",
    heading: "Category",
    multiple: true,
    maxVisible: 5,
    options: [
      { label: "Shirts", value: "shirts", count: 142 },
      { label: "Sneakers", value: "sneakers", count: 87 },
      { label: "Bags", value: "bags", count: 53 },
      { label: "Sunglasses", value: "sunglasses", count: 29 },
      { label: "Sarees", value: "sarees", count: 64 },
      { label: "Loafers", value: "loafers", count: 38 },
      { label: "Umbrellas", value: "umbrellas", count: 12 },
    ],
  },
  {
    id: "brand",
    heading: "Brand",
    multiple: true,
    maxVisible: 4,
    defaultCollapsed: false,
    options: [
      { label: "Aarong", value: "aarong", count: 56 },
      { label: "Yellow", value: "yellow", count: 41 },
      { label: "Westecs", value: "westecs", count: 33 },
      { label: "Ecstasy", value: "ecstasy", count: 27 },
      { label: "Le Reve", value: "le-reve", count: 19 },
    ],
  },
  {
    id: "price",
    heading: "Price Range",
    multiple: false,
    options: [
      { label: "Under ৳1,000", value: "0-1000", count: 95 },
      { label: "৳1,000 – ৳2,000", value: "1000-2000", count: 112 },
      { label: "৳2,000 – ৳3,500", value: "2000-3500", count: 74 },
      { label: "Above ৳3,500", value: "3500-plus", count: 38 },
    ],
  },
  {
    id: "color",
    heading: "Color",
    multiple: true,
    maxVisible: 6,
    options: [
      { label: "Black", value: "black", count: 88 },
      { label: "White", value: "white", count: 76 },
      { label: "Navy", value: "navy", count: 52 },
      { label: "Maroon", value: "maroon", count: 31 },
      { label: "Beige", value: "beige", count: 44 },
      { label: "Gold", value: "gold", count: 22 },
    ],
  },
  {
    id: "rating",
    heading: "Customer Rating",
    multiple: true,
    defaultCollapsed: true,
    options: [
      { label: "4★ & above", value: "4-plus", count: 203 },
      { label: "3★ & above", value: "3-plus", count: 251 },
      { label: "2★ & above", value: "2-plus", count: 268 },
    ],
  },
];

export interface MockAuction extends Omit<LiveAuctionPanelProps, "onExpire"> {
  id: string;
}

// lib/mock/live-auctions.ts
import type { LiveAuctionPanelProps } from "@/components/organisms/LiveAuctionPanel";
import type { BidControlsProps } from "@/components/molecules/BidControls";

export interface MockAuction extends Omit<LiveAuctionPanelProps, "onExpire"> {
  id: string;
}

const now = Date.now();
const mins = (n: number) => new Date(now + 1000 * 60 * n);
const hrs = (n: number) => new Date(now + 1000 * 60 * 60 * n);

export const LIVE_AUCTIONS: MockAuction[] = [
  {
    id: "a1",
    label: "Live Auction",
    title: "Vintage Leica M3 Camera",
    subtitle: "Classic Cameras Collection",
    description: "Fully functional 1958 rangefinder, recently serviced.",
    productImage:
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FtYXJhfGVufDB8fDB8fHww?w=500&h=650&fit=crop",
    productImageAlt: "Vintage Leica camera",
    currentBid: 48500,
    endDate: mins(42),
    recentBidders: [
      { name: "Rafiq Ahmed", amount: 48500 },
      { name: "Sumaiya Karim", amount: 47000 },
      { name: "Tanvir Hossain", amount: 45500 },
    ],
    viewerCount: 312,
    bidControls: {
      minIncrement: 500,
      quickOptions: [
        { label: "+৳500", amount: 500 },
        { label: "+৳1000", amount: 1000 },
        { label: "+৳2500", amount: 2500 },
      ],
      bidStatus: "idle",
      onPlaceBid: (amount) => console.log("a1 bid:", amount),
    },
    dark: true,
    color: "primary",
    size: "md",
    currency: "৳",
  },
  {
    id: "a2",
    label: "Live Auction",
    title: "Hand-Knotted Persian Rug",
    subtitle: "Heritage Textiles",
    description: "8x10 ft silk-wool blend, 40 years old.",
    productImage:
      "https://images.unsplash.com/photo-1600166898405-da9535204843?w=500&h=650&fit=crop",
    productImageAlt: "Hand-knotted Persian rug",
    currentBid: 125000,
    endDate: hrs(2),
    recentBidders: [
      { name: "Nusrat Jahan", amount: 125000 },
      { name: "Imran Kabir", amount: 120000 },
    ],
    viewerCount: 189,
    bidControls: {
      minIncrement: 2500,
      quickOptions: [
        { label: "+৳2500", amount: 2500 },
        { label: "+৳5000", amount: 5000 },
        { label: "+৳10000", amount: 10000 },
      ],
      bidStatus: "idle",
      onPlaceBid: (amount) => console.log("a2 bid:", amount),
    },
    dark: true,
    color: "secondary",
    size: "md",
    currency: "৳",
  },
//   {
//     id: "a3",
//     label: "Live Auction",
//     title: "Signed First-Edition Novel Set",
//     subtitle: "Rare Books",
//     productImage:
//       "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=500&h=650&fit=crop",
//     productImageAlt: "Stack of signed first-edition novels",
//     currentBid: 18200,
//     endDate: mins(15),
//     recentBidders: [{ name: "Farhana Akter", amount: 18200 }],
//     viewerCount: 94,
//     // Previously had no bidControls -> bid section was hidden by design.
//     // Added now so every active (non-ended) auction in this list behaves the same.
//     bidControls: {
//       minIncrement: 200,
//       quickOptions: [
//         { label: "+৳200", amount: 200 },
//         { label: "+৳500", amount: 500 },
//         { label: "+৳1000", amount: 1000 },
//       ],
//       bidStatus: "idle",
//       onPlaceBid: (amount) => console.log("a3 bid:", amount),
//     },
//     dark: true,
//     color: "tertiary",
//     size: "md",
//     currency: "৳",
//   },
//   {
//     id: "a4",
//     label: "Live Auction",
//     title: "Antique Brass Telescope",
//     subtitle: "Maritime Collectibles",
//     description: "19th-century naval telescope, brass and leather.",
//     productImage:
//       "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=500&h=650&fit=crop",
//     productImageAlt: "Antique brass telescope",
//     currentBid: 62000,
//     endDate: mins(-5), // already past
//     recentBidders: [
//       { name: "Kamrul Islam", amount: 62000 },
//       { name: "Shahriar Nafis", amount: 60500 },
//     ],
//     viewerCount: 271,
//     ended: true, // intentional: bid controls hidden because this auction is closed
//     dark: true,
//     color: "neutral",
//     size: "md",
//     currency: "৳",
//   },
  {
    id: "a5",
    label: "Live Auction",
    title: "Mid-Century Teak Armchair",
    subtitle: "Modern Furniture",
    productImage:
      "https://images.unsplash.com/photo-1503602642458-232111445657?w=500&h=650&fit=crop",
    productImageAlt: "Mid-century teak armchair",
    currentBid: 22500,
    endDate: hrs(5),
    recentBidders: [
      { name: "Adiba Chowdhury", amount: 22500 },
      { name: "Rakibul Hasan", amount: 21000 },
      { name: "Mehjabin Tonni", amount: 20000 },
      { name: "Sajid Rahman", amount: 19500 },
    ],
    viewerCount: 158,
    bidControls: {
      minIncrement: 500,
      quickOptions: [
        { label: "+৳500", amount: 500 },
        { label: "+৳1000", amount: 1000 },
        { label: "+৳1500", amount: 1500 },
      ],
      bidStatus: "idle",
      onPlaceBid: (amount) => console.log("a5 bid:", amount),
    },
    dark: false,
    color: "primary",
    size: "md",
    currency: "৳",
  },
  {
    id: "a6",
    label: "Live Auction",
    title: "Limited-Edition Wristwatch",
    subtitle: "Luxury Timepieces",
    description: "Numbered edition, 1 of 250 made worldwide.",
    productImage:
      "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=500&h=650&fit=crop",
    productImageAlt: "Limited-edition wristwatch",
    currentBid: 340000,
    endDate: mins(90),
    recentBidders: [
      { name: "Tahmid Zaman", amount: 340000 },
      { name: "Promila Sen", amount: 335000 },
    ],
    viewerCount: 502,
    bidControls: {
      minIncrement: 5000,
      quickOptions: [
        { label: "+৳5000", amount: 5000 },
        { label: "+৳10000", amount: 10000 },
        { label: "+৳20000", amount: 20000 },
      ],
      bidStatus: "idle",
      onPlaceBid: (amount) => console.log("a6 bid:", amount),
    },
    dark: true,
    color: "warning",
    size: "md",
    currency: "৳",
  },
  {
    id: "a7",
    label: "Live Auction",
    title: "Original Oil Landscape Painting",
    subtitle: "Fine Art",
    productImage:
      "https://images.unsplash.com/photo-1531913764164-f85c52e6e654?w=500&h=650&fit=crop",
    productImageAlt: "Original oil landscape painting",
    currentBid: 95000,
    endDate: hrs(8),
    recentBidders: [{ name: "Lubna Yasmin", amount: 95000 }],
    viewerCount: 76,
    bidControls: {
      minIncrement: 1000,
      quickOptions: [
        { label: "+৳1000", amount: 1000 },
        { label: "+৳2000", amount: 2000 },
        { label: "+৳3000", amount: 3000 },
      ],
      bidStatus: "idle",
      onPlaceBid: (amount) => console.log("a7 bid:", amount),
    },
    dark: true,
    color: "info",
    size: "md",
    currency: "৳",
  },
];
